Fixed Issue #33
ESN-Trondheim/ESNbot pull request #37
Opened 2023-10-29 17:39 UTC by ziegenludwig

Changed concatenating print statements to f-strings to improve reading ability and performance.

2023-10-29 18:53 UTC, LaiAlexander commented
Hi!
Thank you for your contribution!

This is still missing some strings that may be converted to f-strings.
Some examples (this is not a complete list)
https://github.com/ESN-Trondheim/ESNbot/blob/3fdf822eb479f5dad88b9255257d9c24e942f6a7/esnbot/commands.py#L57

https://github.com/ESN-Trondheim/ESNbot/blob/3fdf822eb479f5dad88b9255257d9c24e942f6a7/esnbot/commands.py#L60-L61

https://github.com/ESN-Trondheim/ESNbot/blob/3fdf822eb479f5dad88b9255257d9c24e942f6a7/esnbot/main.py#L31-L32

2023-10-29 21:40 UTC, ziegenludwig commented
I think I should of gotten most if not all now.

2023-11-08 21:21 UTC, LaiAlexander requested changes
Hi again! Apologies for the late reply. 
Please see the comments, and fix those issues. 
Also, there's been quite some changes since you originally submitted this PR. Please merge master into your branch and resolve the merge conflicts.
We have also recently added [contributing guidelines](https://github.com/ESN-Trondheim/ESNbot/blob/master/CONTRIBUTING.md). Please read them and follow the steps, particularly the already mentioned merge from master into your branch, formatting and that all checks needs to pass for a PR to be accepted.

2023-11-08 21:21 UTC, LaiAlexander commented on esnbot/commands.py
> +    log_to_console(f"Arguments supplied by user: {str(argument)}")
There's not really a point in casting this to str, the f-string already does this anyway.

2023-11-08 21:21 UTC, LaiAlexander commented on esnbot/commands.py
> +    log_to_console(f"Arguments supplied by user: {str(argument)}")
There's not really a point in casting this to str, the f-string already does this anyway.

2023-11-08 21:21 UTC, LaiAlexander commented on esnbot/main.py
> +                                  ESNbot connected and running..., w")
`def log_to_file_and_console(filename, message, mode)`

This should take three arguments, not one.

2023-11-15 18:58 UTC, closed without merging